services:
  xarm_controller:
    build:
      context: .
      args:
        ROBOT_IP: ${ROBOT_IP}
        ROBOT_DOF: ${ROBOT_DOF}
        CONTROL_FREQ: ${CONTROL_FREQ}
    env_file:
      - .env
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/workspace/src
    stdin_open: true
    tty: true